### ISSUE TITLE
Feature request: lightline support

### ISSUE THREAD

**Issue by oblitum** [atchim/underworld.vim#1]
Thanks for this colorscheme, really nice! Wished it provided lightline support out of the box.

**Comment by atchim** [comment]
I really appreciate your feedback. I never imagined that someday someone other than me would use this color scheme.

Now talking about lightline support, I spent some time figuring out the best way to implement it. The first thing I did was to take a look at the names and colors of lightline highlighting groups. The names of the groups were very complicated to understand, probably because they should not be handled manually. After that, searching the lightline plugin files, I found a folder containing all the color schemes supported by the plugin. So I created a new file called `underworld.vim` and started to write the necessary configurations based on other color schemes in the same folder. The problem is that the plugin does not recognize any file other than the "official" ones. So, to test the implementation of this color scheme in lightline, I had to edit an existing color scheme called `wombat`. I finished the implementation. The colors are in accordance with the proposal of `underworld`.

The question now is how to make this color scheme be supported in the lightline by default. I will send my implementation to the lightline project. I hope they accept that.

Thanks!

**Comment by oblitum** [comment]
The way it's done for colorschemes to add airline or lightline support is to put the scheme in this directory location, e.g., check:

https://github.com/tyrannicaltoucan/vim-deep-space/tree/master/autoload

**Comment by oblitum** [comment]
I think it's fine to be done independently, as lightline.vim/airline will recognize themes put in that autoload location. But feel free if you think it's needed to provide it builtin to lightline project itself.

**Comment by atchim** [comment]
> The way it's done for colorschemes to add airline or lightline support is to put the scheme in this directory location, e.g., check:
> 
> https://github.com/tyrannicaltoucan/vim-deep-space/tree/master/autoload

Thank you so much for this advice. I will implement it right now.

**Comment by atchim** [comment]
lightline support added. @oblitum, please let me know your feedback about the colors.

**Comment by oblitum** [comment]
@atchim holy moly, this looks great, many thanks!

I was looking for a very dark colorscheme for lower brightness all around, low dark contrast I mean, your colorscheme the sole one I found that hit the mark.

**Comment by oblitum** [comment]
![16:08:13_28-10-2020](https://user-images.githubusercontent.com/1269815/97484700-db6a3b00-1937-11eb-9a06-66a908d37a32.png)
